spring.application.name=invenatario
#datos para el acceso a la base de datos
url=${DB_URL:}
user=${DB_USER:}
password=${DB_PASSWORD:}

#Este parte es las credenciales para enviar coreos electronicos
brevo.smtp.host=${BREVO_SMTP_HOST:smtp-relay.brevo.com}
brevo.smtp.port=${BREVO_SMTP_PORT:587}
brevo.smtp.user=${BREVO_SMTP_USER:}
brevo.smtp.password=${BREVO_SMTP_PASSWORD:}
brevo.smtp.from=${BREVO_SMTP_FROM:}

#clave Tocken de dni
apisperu.api.key=${APISPERU_API_KEY:}
#clave tocken de ruc
apisperu.ruc.api.key=${APISPERU_RUC_API_KEY:}