spring.application.name=invenatario
#datos para el acceso a la base de datos Supabase
url=jdbc:postgresql://db.hugqmdsfjprzaaopzjcl.supabase.co:5432/postgres?sslmode=require
user=postgres
password=Rafael#.cixbd@

#Este parte es las credenciales para enviar correos electronicos Brevo SMTP
brevo.smtp.host=smtp-relay.brevo.com
brevo.smtp.port=587
brevo.smtp.user=bb0ac3001@smtp-brevo.com
brevo.smtp.password=xsmtpsib-ed621b3edc8e40444fdf52327e5e922d1ddb3526ac8f6989eac657e24ce89ce8-GHrfWyqVptubU0ci
brevo.smtp.from=cruzvasquezyhomar@gmail.com

#clave Tocken de dni APIs Peru
apisperu.api.key=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNydXp2YXNxdWV6eWhvbWFyQGdtYWlsLmNvbSIsImp0aSI6IjRlNzU2MjNjMTIzN2Y4ZGQifQ.smrb-Mk2dWJVwRXVDhGUG9qKBTmIAQnc1DKGCs3a-2E
#clave tocken de ruc APIs Peru
apisperu.ruc.api.key=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNydXp2YXNxdWV6eWhvbWFyQGdtYWlsLmNvbSIsImp0aSI6IjRlNzU2MjNjMTIzN2Y4ZGQifQ.smrb-Mk2dWJVwRXVDhGUG9qKBTmIAQnc1DKGCs3a-2E